# Generated by Django 3.1.6 on 2022-07-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finn_code', models.IntegerField(unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
                ('Boat_location', models.CharField(blank=True, max_length=10, null=True)),
                ('State', models.CharField(blank=True, max_length=10, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Model_Year', models.CharField(blank=True, max_length=5, null=True)),
                ('Length_feet', models.CharField(blank=True, max_length=10, null=True)),
                ('Length_cm', models.CharField(blank=True, max_length=10, null=True)),
                ('Width', models.CharField(blank=True, max_length=20, null=True)),
                ('Depth', models.CharField(blank=True, max_length=20, null=True)),
                ('Engine_Included', models.CharField(blank=True, max_length=10, null=True)),
                ('Engine_Manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('Engine_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Motorstr', models.CharField(blank=True, max_length=20, null=True)),
                ('Max_Speed', models.CharField(blank=True, max_length=20, null=True)),
                ('Fuel', models.CharField(blank=True, max_length=20, null=True)),
                ('Weight', models.CharField(blank=True, max_length=20, null=True)),
                ('Material', models.CharField(blank=True, max_length=20, null=True)),
                ('Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Seating', models.CharField(blank=True, max_length=5, null=True)),
                ('Sleeps', models.CharField(blank=True, max_length=5, null=True)),
                ('orignal_price', models.BigIntegerField(blank=True, null=True)),
                ('last_changed', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_price', models.CharField(blank=True, max_length=50, null=True)),
                ('price_changed_date', models.CharField(blank=True, max_length=50, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webapp.listing')),
            ],
            options={
                'unique_together': {('listing', 'changed_price', 'price_changed_date')},
            },
        ),
    ]
