# Generated by Django 4.0.6 on 2023-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_listing_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='finn_code',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='changed_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
