# Generated by Django 4.0.6 on 2023-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_listing_finn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='orignal_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='changed_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
