# Generated by Django 4.0.6 on 2023-06-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_listing_orignal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_history',
            name='last_updated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='changed_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='listing',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webapp.listing'),
        ),
        migrations.AlterField(
            model_name='price_history',
            name='price_changed_date',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
