# Generated by Django 4.0.6 on 2023-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_price_history_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_changed_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
