# Generated by Django 4.0.6 on 2023-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_listing_last_changed_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_history',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='price_history',
            name='last_changed_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
